language: node_js
sudo: false
node_js:
- 5.2
- 4.2
script:
- npm run ci
- chmod 777 ./test/shell_scripts/run_tests.sh
- ./test/shell_scripts/run_tests.sh
after_success:
- cat ./build/reports/coverage/coverage.lcov | node_modules/coveralls/bin/coveralls.js
after_failure:
- for file in *.log; do echo $file; echo "======================"; cat $file; done
  || true
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: Y18jpvZjMu8y5dXuz1i9FvVSXCneuZUWNsvCFsPKvsZmpoX0BBkj0qGQSe/Zfy/SuxQ+7aOK9OII3e/603xSxsSuJYt6iiVclfK4XsQfrbr39CmQZ5SjncfovZiwcCFtWePpJ5naDtkqTWlsvDqVjupwDCNFGXzjAN+figTx5Kt8L0E2mC/QqV73bpSjHgFwBEFLi0gPagAqmGPZYFtTehjcteQnA6hArtYxN5wpWJsaGEG5dY+w3uTg0mp1bMCWFeU+Nv216DePKbglOOcHb8EXG8nrq6Esq26+qMXpdQu4NkK3trOANlk0XI1FseG+RlVGMl7ilSgYj8P4910MMHSmHCgKVCaDXqvcsvNVJvaIM88xdOFJoORO+G1gTGvJAloANb86glQVRr1lwmHLOYtIUAPyMmNlpcjtrKgMpuYyLzRqAo+l31hapG3uhzCyQiHJU15XsQfmPLT3voDwEiL7eSaJppPvvZFX3uRAIDPsFviJyPg0aAJ/1hvA9Lc5etqiwU8Z1M1qSKep8HnI/lf1F2i/2+y/Kr7ezR+En/P5nphOjgbbfHcnJH2VKmymxubEEVJxKJhDJHfXRz0FORu7QvSLaH1FZO+HjLsiaTMoldFkltilQuzkwHstW+wmyzJObweNDrnnZhtjMOEIyK3QZpErQl6Bi2ujpIV3ZiI=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: ZSuh/+b0r75XvGRfl89QfI33u/u0Mg6b3hDGmqjWAuq2Zrs/JgTO26sH7EqedAYV4OGp3VLN+pkRoOvzXgyyz1Zf6O03rgBfjbcBxONBWmQKRjRiNEe2nbBvw97xgVw1VOqvbi19DoJJHwfjZS8fwv7gZh/2iRipQSsdgKv2Dj4wzvJwGKlVyUH2puKVz2gwTxv9eTk2c5QiI1Jex8kZl7acQVtOR50nud5g10s+QuILViAcqnd9bY0dn7bM9OKQ7deViAngD2a0Vgrhtx15vqeCpujLf+F2DM9gPpBR9mcPtU2UAUV9QZtfS8zhn4va8ZIYiDck4EnFC7bHbj4QtoOxt2At+XwcGgEQaLjAeTFsYSXgbOrJkKXF0yGhkcTvsQCg/D09i/LO/1OUNvq0wH4p+uMxIfD2fSUJrqdKewnDBlm4Oc5LxWyN95qT2CCNtLRPRBRM7nTnbSKcEG0gKHpN26zHwLU+dfmhAxqu2I9Nlsi3J84smOpA3gwQsF7BH18jPXJ9pA47gEmdl4Zp6oibga4whkDa9JH+SuzajbzBn5iJWQjiaJm4nTBwiXbjzAg6wYZaHQq7rPJeuLShmVL4cI1D4Iq/XHhVYm/IsXEH9xMDl0/awUq4wtFphRZaMjO0XGzXtSIKIjm5+jY/icgN2GTDo4w7ZeFj4ww6pks=
